key: p3fzkxtu4vE9PJ4PTCQqeI4vx2uEmXsFCd9yRfFnpaEeTlq1uGQ+sx48AbJR7RFuDJnjwH25b2TvoEzl/xPaOeeG8UM/ewVWlBZtBmWUW9tgKwCj+yAQLpVAxSwxCm9RlRycfClNnuzuohcCh4HrwmvOEdTwJJs/DtuWcI7ywbpD52hzmhGrF7GHeY+s2qFzdM9NaulVBCa3DzQSL4ZJ9vN7oJ5mK7orsEHcGteGo3YImdhdxWtwYw9WWb7hXckGEbT+bytO3kc3r9zeigf7vruCCG1abVNG5RdTmQ2nPCg74o0IpTvE/PgVt/vvBPHGsN20HZZUfP/X0Wils4dTvfpo+zVZQk+AsxZau4Ubr6H8GFpE6GQVTAdlbmgSDUukbpHe850oJZCoHJ53cWtFhmD3Hz6+f5m+rVUVt6jHRpvzwmv1NYSTU1UCKNCJyY5Y4QhMt9HEhlQEAiTK8WOkR5wSilGG7XV1aigTn/scoXsshGp3ApNXCsvYcDcExQJtTOShCe1GKvaSD2A5jjbc4l5rSBBk0h0bXC3HdMuvnWU93CcVnvrW9dwjSONI9ZhuzIuTV4L7tn06JGS9ULvbi6Rti3giraMvTJd55s0CYeFijOoZdh8PiOY+GFWsdYrI2pO8V+xwMDewDomzovz5znN3X7ffycnLvlmNir677zV2eofzeOLoEg13UTm5Omg/XOnHKQ//r0qrCri1NFbKADyaHvYz1ieo5SSY5Wro1GNk383mxT9BhaT2bzVgLkNPJ8RHsASIx2BBlGR3jab1pNxANxoIriL6A0ie5c2CsR3otkBUTa0bcMQg8fEUPq/15SL/CLJKhtpte3xjlidUg0pmwPBc2gRBEyinOfSc/cH9zplNSuBOZGxEz0ttcgBkeZsL3vjpkRohtXAfOkH9Op33u+bruHH7ndFHzRI3fUexYw1DP3ytr8UI9m8bS93793iL64iKrYqlHtGZoV55l2d0bEjjrFyqdmaaqVzg6YMPgqDhrzJOxVcN/4XsTwbVZ8IwoQSwPGYCpCbEwZuB+mKWSI0UmzMgalpgv2kFh9XAQd/SBLdAPU+gtrESu/1LOu8EcJBtK8iDcBrYcTX+TA==
tags: 
  Name: ecsinstance
  appName: nodejsappecs
  projectName: nodejsprojectecs
metrics:
  plugins:
    - name: prometheus
      enabled: true
      interval: 100
      config:
        ports: "5000"
