key: 8/iVG9GHbmrT2+H28EFF5u9UiwujtQKySkY3xSTz3OHnkOumaUdeacbakj7vGIx+zaTy8w9CPYXReTh8qHAuAsP8/9rA7wYPFJ7pO6nyNs0/MruX/dt+pnlmSjGIPHWPFIhMDcOdOkXSvITgnZdxazovbUdVcqxz62wFLJFIqL59ALy0/PlhoGD2wFSXsQYTVdVdJyuc2tHIiwKMbxc4PwXidB191rTFhjZFjkgNpqsaDj5ACQTLaPk0xbYwiCABZ7UJuk41PcgX7wTH7MW4QKqydIQLLlsmggL3rh5Tpyk/k/YPYjzGLrL2s4rDLH28MgDuKOZf/vNPFu13hMQ9bXPHfgepx5gMUrqC4tnuH7pyV2IuxN46QH1jH51jssg7xbD8AvVoTNIEHbz5QBv2FkE1wk9DRFZ8NO2NkgfKkk/ZscGiHfVYca3BkFrEel6S02tugUWnFjWPvwU/gT8oveJeY3qd5fhhqqtr9kNRzykf1bbggNdkeUcqe0DTj7mJIivUbO4chiPCTocEv0oJh2EYYHjOHj8kYK3rIP4SFcLEgn0sIi6w93C0NQt8/LtpC2quEnnwGL/+0YVpkCI4IRgPxsQKCjsSop6dkkMQL22T3OPpWEur4qD7FnpGus+e7HegXmaYYFlkyz+ImDK2QWj09yAzGrZVb6zCXSp0i/RJ28SP8C9Vg324GvaSW1Nq5xaIlwJc3JeySBvfzASkNX4UDG04gufJgdhoL739D2r7AD94uL83k8BMNEud11LZZeNg48KWRqqH5ZeYxE1LuvnBw0l0mYrI3LCNjQIw9lWhc+xCeUZWO8BsroWA3qYmrLJ6fKCny/kA8fQf/XXZRnmhb/nuhQkBBQDcHKHTm+xYuCqXGtSy50YrjHQthvkfr4fQkR1cDPHCXeewx1XVHr0Nr93qkspkQfwu/AqYJ59YKaP7Nh9zPPcxd0YkeT+Dsxn9EgTQEflc/CgFzmQ8KI5NvxZjsr5UiY9IlWujSNbAwYYZ/5s7azgnqieN32bHWa40lF4w4dl+5IJRYdrkhRsph+7FyweUuRFw8s/35uoqaL+8sxF4KPk239Tkyfm0DIznniK/qv5aXdriiQY3og==
  Name: ecsinstance
  appName: nodejsappecs
  projectName: nodejsprojectecs
metrics:
  plugins:
    - name: prometheus
      enabled: true
      interval: 100
      config:
        ports: "5000"
