key: +dDDA3cfwxIM79Xu3v/+0EX3ELlMMeWfVeWW15XnRw5Iyb2vWi2Lp/UuUT3YxNp2hBthlImTgX2f6+835+SbsnU+V/Wy+nevQbre09MqDBjaB2JQ5fyN1hkZrwank43QPSQ8t1LxHiynmZ3alk064l7RzgMNMl0LWTyTX+HopG0/u2KsSp+vhvEO7DrmMd3rWJQPcH+BwVNWf54r3zQRdn+ZbOVPHxgQSyYxYXO4j62JXqI9Dxj9WP5IVrUt14IqQ5U5Ar/z/u0FF9c2IfwoWds/td41A35CUC47KwZYcBbRpJRFw7qXFJQGYmgVkf/UgqU3eRxAIsaKzIRygEoeMUSycaDNifsS88oczpMCd+RWQK0BgBYkRdTgt8Lhl2iIXBK7R9REASmRuOkC5JnnHejoFfKGBLzR6kgFFwPvszxQZx5a95bnKQe5EgbFwfNTbvNCpVNS93NlM73LOiXibwK35vbEXz58xwrnFps4dttd5tgQOq/7SwFwT/5KwiStdK3kwkdL4B+Zmfqw//VAUwgPRA6hPYBYJFdrSd7N/ONOX60/1WuvbbrrKiQJs+vXDB1zxf6BvLpsTTP8BwF5+cXzybRA/toT0CIbQ1MGfYY9vB02KGrpHOfjHtEOlrTB30zw5sfPocF9uIxy6uSFVBjXCled7UREPk2nzkz9yAqa90oeH+90/cL6BjXEAoqOSIMFFULRrRX56X+alpATYLhM27miLmHBijxl2Qnxa4xbKjIE4z9iIyx/V2YK5077lktIANtxJLyfmSf+x699wguEDWa4yYujauxLGxdZyGQ4od0Lup8LRE+w76weQK6a+McJuPcE4aKLB9YfrKNvN1uF/BkBtCJiI/8tYxKjUu5tCmxON+/PpXtchD1d/scdmATnvInjL+zlww5URLST9pkGdPhmWa7xF8f3MBY4VcH/JVdXuM+KEAI9pH5akrlAHm+Z/TfGbAnuQC/R4gCWEkl8dvmWizFl3oJcpVq0y2gBTrH3HmKExhtBAjArNsjkOdcYf+ooM2k3MGRqs9e9gw==
  Name: nodejsinstance
  appName: nodejsappecs
  projectName: nodejsprojectecs
metrics:
  plugins:
    - name: prometheus
      enabled: true
      interval: 100
      config:
        ports: "5000"
