key: Fg2QLT0lJwqVQBad7rnbUk5Gu96IZt3ROnxMeOYkcwix3GEuVghzIjlMAAjOe84vMbNYR29VtPqoZLHIULKr3y7l6RUShDfEGuRmWT6859ukGCmPMESSpJseodDDyoiX+6KM9rYZcRJ1Fw8J16DQbTLE1GfSVcRKQITcOIFaxCOJeS53axqpdVcXmtT8ZAMyVuAGSnzaB3L/Q2uztqeH+4sZNdUYTypPPDPeu48AkStFhKAopKybOCMm2h14gipSOgjcw9p3m+kpWh8MRdDCA5FTaQKytRAUfHt5WqIMsv6GjPxZkUtGWOqZlRSrTP55utH1s4mUwqMivz2b92+q7//BivmT845WsQY4ouuJ0ikBEqCoRFQxQiCxjRCoZIv5ASc3dKPbUmFIdP/j2fvh/5PwArmZksWIuNaUg+5aR7xoJd+BH30LJQFUD/I1v6orxSNzf7dKe8Iv31IEsfl/PKZ0I6HmL0pTmdfWOTuSzhPWCDazKQye1usVHdntdvpqCKqzRI6ufNqvFdaBflCUAXDpjo4rQMzndl2Z9KP2oqGYXOjPOGU1C3rMyApv2L7ZzlgmeAmo4pZsqfa5y8t3cjsxaOWvXGfj0VBpuYplEiu9xPznSiv6AtwYx2N6yEJWN4RRAB+ATmwahbENW1ftWR1dRLaOcQpDpzpjWju+dedCd2yAffqLUFxBRkmwm6f8X/QrL5EpQOZ2C+Ta9+juiBSxvOzXBaJxxFBFWRs2xrwQ0DYYdWPNtVRrlSy/pJBGEWV0bPhWOmEMDCfhDTArUFulEg3XYNuHQkuTL1GPtTXxXquWhVVOihB1mN68U7fnX9O35bbswreVOPKml7qKuAbDDzQF/8aa9e5Lpy8EoE0wTOPKvJD11zN3JzDCFM0WJrOnJZJYyW61TAQZUYwG8xlTN6KUriPkrQ5kjHeXbVxmDP7VCeZujNQICGsqHbGy7yUl5TzMBXT8uAvqhcvTmIvAmxo+81btKfx4gcaFz9I8nWEA0BMc6V3W83H1xYiS7GCk+8hIE1+eGHgwAFegq2D7M4Q0eb6xD0OWjhtWP+FnFlam8ZBsw7aLb7cD2ATc4pXEpIWH/yv7acsPVFmiCA==
tags: 
  Name: ecsinstance
  appName: nodejsappecs
  projectName: nodejsprojectecs
metrics:
  plugins:
    - name: prometheus
      enabled: true
      interval: 100
      config:
        ports: "5000"
