key: zZvDkpfLzw1pGKNf/wlYZ66A2hAqmE/g7nFZHFPmyuIp6v5Xzyz8+5wHdyHR5tPaA5XwV5MXU3NJNN3d+SJbsBfLKNvhnYcrA8IG8gAyKuqX+2gIvKPfuFmQlEbV9V0DdKWQS1y+t/4BeC3hy1T8YqASCvOHKLDqdiJH0YK/JjDgBkZvE1UVOyA/105XDYwNWnaSYP6qk84XQ8q8HgjWbn7477V8NQMYD4u7jsdr8dumIZx9srZ00QAFBbKW9zw4H9YeHUgYAj0JUDBERKKBKWnSyMW2x063H0jweC6bysaaCQh7RUI8NpeK3JXdfPHGCc4EeMV0crwwpJeG7qOai+nEB3h2n5mWs27FqZZgnOiVt9KNbDMTFC7RmE4woI3ZSw10kWIPzbUbhBEsBlC0gVgwib6MEhU5CkE/yyA2jRQl15rQ9ffsxmZWU/AWDmk4xCn20HQU8zwXk8tBHbfMD44BDnZk3hIeJMfgo+EVwWVc1/5k3Qjh0E5kbO9+uhNGo7LBwj329tHfjQBCpisOE69F5k8yQxN4nTDBUEin2qQTMCqBxHdVfgh17ChyI4Bl6TtvgtTCrkspVcLmuDdO61w5cPCcZIIDJtiLZZuG6Xf3pB9TSmJEqmsd9kUxwITuqSEzM/WlBgfuWSvf77aWb0RZR0cdV1SgHJyb989+rhpqKkX1CgUTlsQ9rdiehPY5iQxpnP9VLRDuYsc9iY+hytE0Fdof0MPc+EFLp1NinsR5r3zm9v78Wa/WaVh83PgheWApWvq0MTE/TexQYYXoMGoRHhhMniXTkd3SWYPNEvmO0K0KznRx2mYiWoXFk+7P99hxlY/9374tW2kkJu3MAiL7o9pAdf5CXjzel8DiaJZ1b7MSmw8uBClS7ycj3hbuVKbohDb37IffzzpPVUwpgGj64wcXTYhYnTXburnb3J5kvLK2SAbGU6zl2ADfMBKNpSYIHGzBsPc+M4vCDfbU8Emxknz2F616BQgmetPPJVUcpNbckdan3vvhARTorPDdQGomiZ8swcO3iQDONYaERw==
tags:
  Name: NODEJS_INSTANCE
  appName: NODEJS_APP_ECS
  projectName: NODEJS_Project_ECS
metrics:
  plugins:
    - name: prometheus
      enabled: true
      interval: 100
      config:
        ports: "5000"
